# dvc.yaml
stages:

  feature_engineering:
    cmd: conda run -n churn-env python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
    params:
      - params.yaml:
          - random_state
          - test_size
    outs:
      - data/processed/processed_data_X_train.csv
      - data/processed/processed_data_X_test.csv
      - data/processed/processed_data_y_train.csv
      - data/processed/processed_data_y_test.csv

  train:
    cmd: conda run -n churn-env python src/train.py
    deps:
      - src/train.py
      - data/processed/processed_data_X_train.csv
      - data/processed/processed_data_y_train.csv
    params:
      - params.yaml:
          - xgboost
          - lightgbm
          - logistic_regression

  evaluate:
    cmd: conda run -n churn-env python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/processed_data_X_test.csv
      - data/processed/processed_data_y_test.csv
    metrics:
      - evaluation_results/metrics_Logistic_Regression.json:
          cache: false
    plots:
      - evaluation_results/confusion_matrix_Logistic_Regression.png:
          cache: false