stages:
  feature_engineering:
    cmd: python scripts/run_stage.py src/feature_engineering.py
    deps:
      - scripts/run_stage.py
      - src/feature_engineering.py
      - data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
    params:
      - params.yaml:
          - random_state
          - test_size
    outs:
      - data/processed/processed_data_X_train.csv
      - data/processed/processed_data_X_test.csv
      - data/processed/processed_data_y_train.csv
      - data/processed/processed_data_y_test.csv

  train:
    cmd: python scripts/run_stage.py src/train.py
    deps:
      - scripts/run_stage.py
      - src/train.py
      - data/processed/processed_data_X_train.csv
      - data/processed/processed_data_y_train.csv
    params:
      - params.yaml:
          - xgboost
          - lightgbm
          - logistic_regression

  tune:
    cmd: python scripts/run_stage.py src/tune.py
    deps:
      - scripts/run_stage.py
      - src/tune.py
      - data/processed/processed_data_X_train.csv
      - data/processed/processed_data_X_test.csv
      - data/processed/processed_data_y_train.csv
      - data/processed/processed_data_y_test.csv
    params:
      - params.yaml:
          - random_state
          - xgboost
          - lightgbm
    outs:
      - best_xgb_params.yaml
      - best_lgbm_params.yaml

  evaluate:
    cmd: python scripts/run_stage.py src/evaluate.py
    deps:
      - scripts/run_stage.py
      - src/evaluate.py
      - data/processed/processed_data_X_test.csv
      - data/processed/processed_data_y_test.csv
    metrics:
      - evaluation_results/metrics_Logistic_Regression.json
    plots:
      - evaluation_results/confusion_matrix_Logistic_Regression.png
