name: ML pipeline CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

jobs:
    code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install linter
        run: pip install flake8

      - name: Run flake8
        run: flake8 src/ --max-line-length=100 --ignore=E402
        